const SOCKET_EVENTS = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  JOIN_ROOM_PREVIEW: "join_room_preview",
  NEW_PEER_JOINED: "new_peer_joined",
  JOIN_ROOM: "join_room",
  ROOM_UPDATE: "room_update",
  CREATE_WEB_RTC_TRANSPORT: "create_webrtc_transport",
  PRODUCE: "produce",
  CONSUME: "consume",
  TRANSPORT_SEND_CONNECT: "transport_send_connect",
  TRANSPORT_RECV_CONNECT: "transport-recv-connect",
  TRANSPORT_PRODUCE: "transport_produce",
  CONSUMER_RESUME: "consumer-resume",
  GET_PRODUCERS: "get_producers",
  NEW_PRODUCER: "new_producer",
  PEER_LEAVED: "peer_leave",
  STOP_PRODUCING: "stop_producing",
  SOME_PRODUCER_CLOSED: "some_producer_closed",
  CHAT_MSG_TO_SERVER: "chat_msg_to_server",
  CHAT_MSG_FROM_SERVER: "chat_msg_from_server",
  RAISE_HAND_TO_SERVER: "raise_hand_to_server",
  RAISE_HAND_FROM_SERVER: "raise_hand_from_server",
  UPLOAD_FILE_TO_SERVER: "upload_file_to_server",
  UPLOAD_FILE_FROM_SERVER: "upload_file_from_server",
  QUESTION_SENT_TO_SERVER: "question_sent_to_server",
  QUESTION_SENT_FROM_SERVER: "question_sent_from_server",
  ANSWER_SENT_TO_SERVER: "answer_sent_to_server",
  START_RECORDING: "start_recording",
  STOP_RECORDING: "stop_recording",
  IS_AUDIO_STREAM_ENABLED_TO_SERVER: "is_audio_stream_enabled_to_server",
  IS_AUDIO_STREAM_ENABLED_FROM_SERVER: "is_audio_stream_enabled_from_server",
  KICK_OUT_FROM_CLASS_TO_SERVER: "kick_out_from_class_to_server",
  KICK_OUT_FROM_CLASS_FROM_SERVER: "kick_out_from_class_from_server",
  PRODUCER_PAUSE: "producer_pause",
  PRODUCER_RESUME: "producer_resume",
  PRODUCER_PAUSED: "producer_paused", // if producer pause is trigger then in frontend we need to pause the video
  PRODUCER_RESUMED: "producer_resumed", // if producer resume is trigger then in frontend we need to resume the video
  PRODUCER_CLOSED: "producer-closed",
  REPLACE_TRACK: "replace_track",
  REPLACED_TRACK: "replaced_track",
  LEAVE_ROOM: "leave_room",
  END_MEET_TO_SERVER: "END_MEET_TO_SERVER",
  END_MEET_FROM_SERVER: "END_MEET_FROM_SERVER",
  MIRO_BOARD_DATA_TO_SERVER: "miro_board_data_to_server",
  MIRO_BOARD_DATA_FROM_SERVER: "miro_board_data_from_server",
  CONNECT_ERROR: "connect_error",
  LEADERBOARD_FROM_SERVER: "leaderboard_from_server",
  LEADERBOARD_AVERAGE_ANSWER_FROM_SERVER:
    "leaderboard_average_answer_from_server",
  BLOCK_OR_UNBLOCK_MIC_TO_SERVER: "block_or_unblock_mic_to_server",
  BLOCK_OR_UNBLOCK_MIC_FROM_SERVER: "block_or_unblock_mic_FROM_server",
  PEER_MIC_BLOCKED_OR_UNBLOCKED_FROM_SERVER:
    "peer_mic_blocked_or_unblocked_from_server",
  MUTE_MIC_COMMAND_BY_MENTOR_TO_SERVER: "mute_mic_command_by_mentor_to_server",
  MUTE_MIC_COMMAND_BY_MENTOR_FROM_SERVER:
    "mute_mic_command_by_mentor_from_server",
  QUESTION_MSG_SENT_TO_SERVER: "question_msg_sent_to_server",
  QUESTION_MSG_SENT_FROM_SERVER: "question_msg_sent_from_server",
  POLL_TIME_INCREASE_TO_SERVER: "poll_time_increase_to_server",
  POLL_TIME_INCREASE_FROM_SERVER: "poll_time_increase_from_server",
};

export default SOCKET_EVENTS;
