const topicDescriptionConstants = {
    '36': 'Study of electric current that periodically reverses direction, commonly used in power transmission.',
    '37': 'Exploration of the fundamental structure and properties of atoms, crucial for understanding chemistry and quantum physics.',
    '44': 'Introduction to essential mathematical concepts and vector operations, providing a foundation for various scientific disciplines.',
    '18': 'Measurement of heat transfer in various processes, important in calorimetry experiments and thermodynamics.',
    '32': 'Understanding the behavior and applications of capacitors in electrical circuits, which store and release electrical energy.',
    '7': 'Analysis of the center of mass and principles of momentum conservation in physics, vital for studying collisions and motion.',
    '5': 'Study of objects moving in circular paths and the associated principles, found in celestial orbits and amusement park rides.',
    '43': 'Examination of communication systems and logic gate operations in electronics, forming the backbone of modern technology.',
    '3': 'Investigation of constraints in mechanical systems, a key concept in classical mechanics and engineering.',
    '33': 'Study of the flow of electric charge in conductors, underpinning electrical circuits and electronics.',
    '24': "Exploration of the change in frequency or wavelength of a wave in relation to an observer's motion, used in radar and astronomy.",
    '11': 'Analysis of the behavior of materials under deformation and stress, crucial in engineering and material science.',
    '35': 'Understanding electromagnetic induction and its applications, including power generation and transformers.',
    '51': 'Study of electromagnetic radiation and its properties, encompassing radio waves, microwaves, and light.',
    '31': 'Examination of electric charges and static electric fields, foundational for understanding electrical phenomena.',
    '13': 'Investigation of the expansion of materials with changes in temperature, relevant in engineering and thermodynamics.',
    '10': 'Study of the behavior of fluids (liquids and gases) and their applications, critical in engineering, aerodynamics, and hydrodynamics.',
    '53': 'Analysis of forced and damped oscillatory motion, essential in resonance and damping systems.',
    '4': 'Examination of the force that opposes the relative motion of two surfaces in contact, influencing everyday mechanics.',
    '46': 'An overview of general physics principles and dimensional analysis, providing problem-solving tools in physics.',
    '9': 'Exploration of the force of gravity and its effects on objects, fundamental for understanding celestial bodies and planetary motion.',
    '16': 'Study of the transfer of heat through solids, vital in thermodynamics and materials science.',
    '23': 'Analysis of interference patterns and beat phenomena in waves, commonly seen in optics and acoustics.',
    '1': 'Study of the motion of objects without considering the forces that cause the motion, forming the basis of classical mechanics.',
    '14': 'Understanding the behavior of gases based on the kinetic theory, fundamental to the field of thermodynamics.',
    '49': 'Examination of Newton laws of motion, describing the fundamental principles governing motion.',
    '54': 'Study of magnetic materials and classical magnetism, central in electromagnetism and technology.',
    '34': 'Analysis of magnetic fields and their properties, vital for magnetic applications and electrical machinery.',
    '2': 'Overview of Isaac Newton laws of motion, the cornerstone of classical mechanics.',
    '41': 'Exploration of the properties and behavior of atomic nuclei, with applications in nuclear energy and particle physics.',
    '52': 'Study of optical devices and instruments, facilitating scientific observations and communication technologies.',
    '39': 'Investigation of the emission of electrons from materials when exposed to light, essential in quantum mechanics.',
    '48': 'Examination of the properties and behavior of matter, relevant in chemistry and materials science.',
    '19': 'Study of the emission and transmission of energy in various forms, including electromagnetic radiation and nuclear decay.',
    '40': 'Analysis of the spontaneous decay of radioactive substances, with applications in radiology and nuclear physics.',
    '25': 'Exploration of reflection in both spherical and plane mirrors, relevant in optics and imaging.',
    '26': 'Study of the bending of light as it passes through different surfaces, essential in lenses and prisms.',
    '8': 'Examination of the motion and behavior of rotating objects, important in mechanics and engineering.',
    '17': 'Study of the second law of thermodynamics, which deals with energy transfer and entropy, fundamental in thermodynamics.',
    '42': 'Understanding semiconductors and their role in electronic devices, powering modern electronics.',
    '30': 'Analysis of periodic motion characterized by simple harmonic oscillations, seen in pendulums and springs.',
    '50': 'Exploration of the properties and behavior of sound waves, important in acoustics and music.',
    '22': 'Study of stationary waves and their characteristics, present in musical instruments and standing wave phenomena.',
    '12': 'Examination of surface tension and the resistance of fluids to flow, relevant in fluid dynamics and chemistry.',
    '27': 'Understanding the behavior and applications of lenses in optics, critical for imaging and vision correction.',
    '28': 'Analysis of the behavior and uses of prisms in optics, often employed in spectroscopy and dispersion of light.',
    '15': 'Study of various processes in thermodynamics, including heating, cooling, and work, fundamental for energy systems.',
    '21': 'Exploration of the characteristics of traveling waves, found in various forms of wave propagation.',
    '29': 'Study of the behavior of light as a wave, important in optical phenomena and technologies like lasers.',
    '6': 'Examination of the concepts of work, power, and energy in physics, fundamental for understanding mechanical systems.',
    '38': 'Understanding the properties and applications of X-rays, crucial in medical imaging and materials analysis.',
  };
  
  export default topicDescriptionConstants;
