const topicDescriptionConstants = {
  36: "Study of electric current that periodically reverses direction, commonly used in power transmission. It is characterized by a continuous, smooth flow of charge in both directions.",
  37: "Exploration of the fundamental structure and properties of atoms, crucial for understanding chemistry and quantum physics.",
  44: "Introduction to essential mathematical concepts and vector operations, providing a foundation for various scientific disciplines.",
  18: "Measurement of heat transfer in various processes, important in calorimetry experiments and thermodynamics. Explores techniques for quantifying heat transfer.",
  32: "Understanding the behavior and applications of capacitors in electrical circuits, which store and release electrical energy. Examines the principles governing capacitor behavior in electronic systems.",
  7: "Analysis of the center of mass and principles of momentum conservation in physics, vital for studying collisions and motion.",
  5: "Study of objects moving in circular paths and the associated principles, found in celestial orbits and amusement park rides.",
  43: "Examination of communication systems and logic gate operations in electronics, forming the backbone of modern technology.",
  3: "Investigation of constraints in mechanical systems, a key concept in classical mechanics and engineering.Explores the role of constraints in understanding system dynamics.",
  33: "Study of the flow of electric charge in conductors, underpinning electrical circuits and electronics. It explores the behavior of electrons and the principles governing the movement of charge through various materials.",
  24: "Exploration of the change in frequency or wavelength of a wave in relation to an observer's motion, used in radar and astronomy.",
  11: "Analysis of the behavior of materials under deformation and stress, crucial in engineering and material science.Investigates how materials respond to external forces and stressors.",
  35: "Understanding electromagnetic induction and its applications, including power generation and transformers. Explores principles behind electrical energy conversion.",
  51: "Study of electromagnetic radiation and its properties, encompassing radio waves, microwaves, and light. Investigates characteristics of diverse electromagnetic waves.",
  31: "Examination of electric charges and static electric fields, foundational for understanding electrical phenomena. Analyzes properties and behavior of static electric fields.",
  13: "Investigation of the expansion of materials with changes in temperature, relevant in engineering and thermodynamics. Explores thermal expansion in diverse materials.",
  10: "Study of the behavior of fluids (liquids and gases) and their applications, critical in engineering, aerodynamics, and hydrodynamics.",
  53: "Analysis of forced and damped oscillatory motion, essential in resonance and damping systems. It involves studying how external forces and damping factors impact the motion, providing insights into dynamic systems and their response to applied forces.",
  4: "Examination of the force that opposes the relative motion of two surfaces in contact, influencing everyday mechanics. Studies frictional forces and their impact on motion.",
  46: "An overview of general physics principles and dimensional analysis, providing problem-solving tools in physics. Explores foundational concepts for problem-solving in physics.",
  9: "Exploration of the force of gravity and its effects on objects, fundamental for understanding celestial bodies and planetary motion.",
  16: "Study of the transfer of heat through solids, vital in thermodynamics and materials science. This field explores the mechanisms of heat conduction in solid materials, investigates thermal properties, and plays a crucial role in understanding how materials respond to temperature variations, influencing advancements in thermodynamics and materials engineering.",
  23: "Analysis of interference patterns and beat phenomena in waves, commonly seen in optics and acoustics.Investigates wave interference and beat patterns in different mediums.",
  1: "Study of the motion of objects without considering the forces that cause the motion, forming the basis of classical mechanics.",
  14: "Understanding the behavior of gases based on the kinetic theory, fundamental to the field of thermodynamics. Explores gas behavior through kinetic theory principles.",
  49: "Examination of Newton's laws of motion, describing the fundamental principles governing motion. This field involves a detailed exploration of the three laws proposed by Sir Isaac Newton, providing a comprehensive understanding of the relationships between force, mass, and acceleration, and forming the cornerstone of classical mechanics.",
  54: "Study of magnetic materials and classical magnetism, central in electromagnetism and technology. Investigates classical magnetism and magnetic materials in depth.",
  34: "Analysis of magnetic fields and their properties, vital for magnetic applications and electrical machinery.Explores the behavior and applications of magnetic fields in various contexts.",
  2: "Overview of Isaac Newton's laws of motion, the cornerstone of classical mechanics. This field provides a foundational understanding of the three laws formulated by Sir Isaac Newton, governing the motion of objects and serving as fundamental principles in classical mechanics, laying the groundwork for the study of dynamics and kinematics.",
  41: "Exploration of the properties and behavior of atomic nuclei, with applications in nuclear energy and particle physics.Investigates the characteristics and applications of atomic nuclei.",
  52: "Study of optical devices and instruments, facilitating scientific observations and communication technologies.Explores the design and applications of optical tools.",
  39: "Investigation of the emission of electrons from materials when exposed to light, essential in quantum mechanics. Examines the photoelectric effect and its implications in quantum theory.",
  48: "Examination of the properties and behavior of matter, relevant in chemistry and materials science. This field encompasses the study of the physical and chemical characteristics of substances, exploring their composition, structure, and interactions. It plays a crucial role in both chemistry and materials science, contributing to advancements in diverse scientific and industrial applications.",
  19: "Study of the emission and transmission of energy in various forms, including electromagnetic radiation and nuclear decay.",
  40: "Analysis of the spontaneous decay of radioactive substances, with applications in radiology and nuclear physics.",
  25: "Exploration of reflection in both spherical and plane mirrors, relevant in optics and imaging. This field delves into the study of how light interacts with reflective surfaces, providing insights into image formation and the principles behind various optical devices.",
  26: "Study of the bending of light as it passes through different surfaces, essential in lenses and prisms. This field involves a detailed examination of how light is refracted when it transitions between different media, contributing to the design and functionality of optical components such as lenses and prisms.",
  8: "Examination of the motion and behavior of rotating objects, important in mechanics and engineering. This field explores the dynamics of rotating systems, covering aspects such as angular momentum, torque, and rotational motion. It is fundamental to understanding the behavior of spinning objects and plays a crucial role in mechanical engineering applications.",
  17: "Study of the second law of thermodynamics, which deals with energy transfer and entropy, fundamental in thermodynamics. Analyzes principles governing energy direction and system states.",
  42: "Understanding semiconductors and their role in electronic devices, powering modern electronics. This field encompasses the study of semiconductor materials, their unique electronic properties, and their applications in the design and development of electronic components, such as transistors and diodes, which form the foundation of modern electronic technology.",
  30: "Analysis of periodic motion characterized by simple harmonic oscillations, seen in pendulums and springs.Examines the behavior of systems undergoing repetitive motion.",
  50: "Exploration of the properties and behavior of sound waves, important in acoustics and music. This field delves into the physical characteristics of sound, including frequency, amplitude, and resonance, providing insights into the creation, transmission, and reception of sound in various environments.",
  22: "Study of stationary waves and their characteristics, present in musical instruments and standing wave phenomena. Explores wave patterns in various mediums.",
  12: "Examination of surface tension and the resistance of fluids to flow, relevant in fluid dynamics and chemistry. Investigates fluid behaviors in different conditions.",
  27: "Understanding the behavior and applications of lenses in optics, critical for imaging and vision correction. Explores lens design and their impact on optical systems.",
  28: "Analysis of the behavior and uses of prisms in optics, often employed in spectroscopy and dispersion of light.Explores practical applications in scientific instruments.",
  15: "Study of various processes in thermodynamics, including heating, cooling, and work, fundamental for energy systems.Investigates the principles governing energy transformations.",
  21: "Exploration of the characteristics of traveling waves, found in various forms of wave propagation. This field of study involves understanding how waves travel through different mediums, examining factors like wavelength, frequency, and amplitude, and exploring their applications across diverse scientific and technological domains.",
  29: "Study of the behavior of light as a wave, important in optical phenomena and technologies like lasers. It delves into the wave nature of light, including concepts such as interference and diffraction, providing the foundation for understanding various optical phenomena.",
  6: "Examination of the concepts of work, power, and energy in physics, fundamental for understanding mechanical systems.It explores the mathematical relationships involved in calculating work done, power exerted, and the energy stored or transferred.",
  38: "Understanding the properties and applications of X-rays, crucial in medical imaging and materials analysis.Provides insights into non-invasive imaging techniques.",
};

export default topicDescriptionConstants;
