export const IS_LOADING = "IS_LOADING";
export const IS_ERROR = "IS_ERROR";

// AUTH RELATED CONSTANTS
export const SIGN_IN = "SIGN_IN";
export const SET_USER = "SET_USER";

// SOCKET RELATED CONSTANTS

export const IS_PEER_LOADING = "IS_PEER_LOADING";
export const SET_SOCKET = "SET_SOCKET";
export const SET_ALL_PEERS = "SET_ALL_PEERS";
export const SET_NEW_PEER_JOINED = "SET_NEW_PEER_JOINED";
export const SET_RTP_CAPABILITIES = "SET_RTP_CAPABILITIES";
export const SET_PEER_LEAVED = "SET_PEER_LEAVED";
export const SET_CONSUMERS = "SET_CONSUMERS";
export const SET_MENTOR_CONSUMER_SCREEN_SHARE =
  "SET_MENTOR_CONSUMER_SCREEN_SHARE";

export const SET_MENTOR_VIDEO_SHARE_CONSUMER =
  "SET_MENTOR_VIDEO_SHARE_CONSUMER";

export const SET_AUDIO_CONSUMERS = "SET_AUDIO_CONSUMERS";
export const SET_CHAT_MESSAGE = "SET_CHAT_MESSAGE";
export const SET_RAISE_HAND = "SET_RAISE_HAND";
export const SET_FILE_UPLOAD = "SET_FILE_UPLOAD";
export const SET_QUESTION = "SET_QUESTION";
export const SET_MENTOR_VIDEO_SHARE_PAUSE_OR_RESUME =
  "SET_MENTOR_VIDEO_SHARE_PAUSE_OR_RESUME";
export const SET_MENTOR_SCREEN_SHARE_PAUSE_OR_RESUME =
  "SET_MENTOR_SCREEN_SHARE_PAUSE_OR_RESUME";
export const SET_FILE_UPLOAD_IN_ROOM = "SET_FILE_UPLOAD_IN_ROOM";
export const SET_MIRO_BOARD_DATA = "SET_MIRO_BOARD_DATA";
export const SET_LEADERBOARD = "SET_LEADERBOARD";

// STREAM CONTROLS RELATED CONSTANTS
export const IS_VIDEO_LOADING = "IS_VIDEO_LOADING";
export const SET_VIDEO_CONTROL = "SET_VIDEO_CONTROL";
export const SET_AUDIO_CONTROL = "SET_AUDIO_CONTROL";

// Schedule classes related constants

export const ADD_CLASS_SCHEDULE = "ADD_CLASS_SCHEDULE";
export const GET_ALL_LIVE_CLASSES_SCHEDULE = "GET_ALL_LIVE_CLASSES_SCHEDULE";
export const GET_LIVE_CLASS_DETAILS = "GET_LIVE_CLASS_DETAILS";
export const GET_UPCOMING_CLASS_DETAILS = "GET_UPCOMING_CLASS_DETAILS";
export const IS_SCHEDULE_CLASS_LOADING = "IS_SCHEDULE_CLASS_LOADING";

// Generic constants

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
